name: BetterTools
main: me.desertdweller.bettertools.BetterTools
version: 0.1.11
author: Desertdweller
api-version: 1.13
depend: [NBTAPI]
softdepend: [CoreProtect,SimpleBlocks]
commands:
  bt:
    description: General BetterTools command.
    usage: /bt
  bt help:
    description: Gives help for BetterTools.
    usage: /bt help <command>
  bt tool:
    description: Gives the painter tool. It is also optional to set the radius as a second parameter.
    usage: /bt tool [radius]
  bt settool:
    description: Set the held tool to the material.
    usage: /bt settool <material>
  bt radius:
    description: Sets the radius of the held tool.
    usage: /bt radus <radius>
  bt mask:
    description: Adds a list of blocks as a mask to the tool. Use official material names, and separate them with commas, no spaces.
    usage: /bt mask <block list>
  bt blocks:
    description: Sets the tool's blocks.
    usage: /bt blocks <block list>
  bt blockupdates:
    description: Sets the tool to whether or not it will update blocks.
    usage: /bt updateblocks <true/false>
  bt through:
    description: Sets the blocks the tool will go through when selecting the origin.
    usage: /bt through <block list>
  bt touching:
    description: Sets the touching limit for the tool you are holding. Meaning that blocks will only be changed when they are next to whatever you set here. Use '/bt touching any' to reset.
    usage: /bt touching <block list>
  bt undo:
    description: Undoes the previous action.
    usage: /bt undo
  bt noise:
    description: Sets the noise parameters for the tool you are holding.
    usage: /bt noise <scale> <xskew> <yskew> <zskew> <min> <max> <frequency> <none/turb/perlin)>
  bt refreshtool:
    description: Refreshes the lore for the tool you are holding.
    usage: /bt refreshtool
  bt snowtool:
    description: Creates a snow tool.
    usage: /bt snowtool [radius]
  bt blockdatatest:
    description: A dev tool.
    useage: /bt blockdatatest
permissions:
   bt.use:
      description: Allows the player to use the tools.
      default: op
   bt.create:
      description: Allows the player to create and edit the tools.
      default: op